In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport 

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df['Pregnancies'].unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14],
      dtype=int64)

In [5]:
len(df['Pregnancies'].unique())

17

In [6]:
# ProfileReport(df)

In [7]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [9]:
#replace

In [10]:
len(df[df['Pregnancies']==0])

111

In [11]:
df['Pregnancies'] = df['Pregnancies'].replace(0,df['Pregnancies'].mean())

In [12]:
len(df[df['Pregnancies']==0])

0

In [13]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0       6.000000      148             72             35        0  33.6   
1       1.000000       85             66             29        0  26.6   
2       8.000000      183             64              0        0  23.3   
3       1.000000       89             66             23       94  28.1   
4       3.845052      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763    10.000000      101             76             48      180  32.9   
764     2.000000      122             70             27        0  36.8   
765     5.000000      121             72             23      112  26.2   
766     1.000000      126             60              0        0  30.1   
767     1.000000       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [14]:
df['BloodPressure'] = df['BloodPressure'].replace(0,df['BloodPressure'].mean())
len(df[df['BloodPressure']==0])

0

In [15]:
df['SkinThickness'] = df['SkinThickness'].replace(0,df['SkinThickness'].mean())
len(df[df['SkinThickness']==0])

0

In [16]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [17]:
#Outliers

In [101]:
fig , ax = plt.subplots(figsize = (40,20))
sns.boxplot(data = df , ax = ax)

<AxesSubplot:>

In [19]:
q = df['Pregnancies'].quantile(.98)    #Remove the 2% data of Pregnancies
df_new = df[df['Pregnancies']<q]


In [20]:
q = df['BMI'].quantile(.99)            #Remove the 1% data of BMI
df_new = df_new[df_new['BMI']<q]

In [21]:
q = df['SkinThickness'].quantile(.99)            #Remove the 1% data of SkinThickness
df_new = df_new[df_new['SkinThickness']<q]

In [22]:
q = df['DiabetesPedigreeFunction'].quantile(.99)            #Remove the 1% data of DiabetesPedigreeFunction
df_new = df_new[df_new['DiabetesPedigreeFunction']<q]

In [23]:
q = df['Age'].quantile(.99)            #Remove the 1% data of Age
df_new = df_new[df_new['Age']<q]

In [24]:
df_new

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0      148           72.0      35.000000        0  33.6   
1            1.0       85           66.0      29.000000        0  26.6   
2            8.0      183           64.0      20.536458        0  23.3   
3            1.0       89           66.0      23.000000       94  28.1   
5            5.0      116           74.0      20.536458        0  25.6   
..           ...      ...            ...            ...      ...   ...   
763         10.0      101           76.0      48.000000      180  32.9   
764          2.0      122           70.0      27.000000        0  36.8   
765          5.0      121           72.0      23.000000      112  26.2   
766          1.0      126           60.0      20.536458        0  30.1   
767          1.0       93           70.0      31.000000        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
5                       0.201   30        0  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[716 rows x 9 columns]

In [25]:
#define x and y

In [35]:
x = df_new.drop(columns=['Outcome'])

In [36]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0      148           72.0      35.000000        0  33.6   
1            1.0       85           66.0      29.000000        0  26.6   
2            8.0      183           64.0      20.536458        0  23.3   
3            1.0       89           66.0      23.000000       94  28.1   
5            5.0      116           74.0      20.536458        0  25.6   
..           ...      ...            ...            ...      ...   ...   
763         10.0      101           76.0      48.000000      180  32.9   
764          2.0      122           70.0      27.000000        0  36.8   
765          5.0      121           72.0      23.000000      112  26.2   
766          1.0      126           60.0      20.536458        0  30.1   
767          1.0       93           70.0      31.000000        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
5                       0.201   30  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[716 rows x 8 columns]

In [39]:
y = df_new['Outcome']

In [40]:
y

0      1
1      0
2      1
3      0
5      0
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 716, dtype: int64

In [56]:
#Standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
x_scaled

array([[ 7.11590111e-01,  8.74344160e-01,  1.13134907e-03, ...,
         2.64629474e-01,  5.98763478e-01,  1.58854720e+00],
       [-1.19593706e+00, -1.10895647e+00, -5.03832349e-01, ...,
        -6.90865753e-01, -3.48179369e-01, -1.35198202e-01],
       [ 1.47460098e+00,  1.97617784e+00, -6.72153582e-01, ...,
        -1.14131350e+00,  7.53156333e-01, -4.44747601e-02],
       ...,
       [ 3.30084677e-01,  2.43581748e-02,  1.13134907e-03, ...,
        -7.45465480e-01, -7.11860317e-01, -2.25921645e-01],
       [-1.19593706e+00,  1.81762987e-01, -1.00879605e+00, ...,
        -2.13118139e-01, -3.55041274e-01,  1.31637687e+00],
       [-1.19593706e+00, -8.57108773e-01, -1.67189884e-01, ...,
        -1.72168344e-01, -4.71693653e-01, -8.60985741e-01]])

In [46]:
x_scaled.shape[1]

8

In [44]:
x_df = pd.DataFrame(x_scaled,columns = x.columns)
x_df

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.711590  0.874344       0.001131       1.005511 -0.708090  0.264629   
1      -1.195937 -1.108956      -0.503832       0.325119 -0.708090 -0.690866   
2       1.474601  1.976178      -0.672154      -0.634635 -0.708090 -1.141314   
3      -1.195937 -0.983033      -0.503832      -0.355272  0.136149 -0.486117   
4       0.330085 -0.133047       0.169453      -0.634635 -0.708090 -0.827365   
..           ...       ...            ...            ...       ...       ...   
711     2.237612 -0.605261       0.337774       2.479694  0.908538  0.169080   
712    -0.814432  0.055839      -0.167190       0.098322 -0.708090  0.701427   
713     0.330085  0.024358       0.001131      -0.355272  0.297812 -0.745465   
714    -1.195937  0.181763      -1.008796      -0.634635 -0.708090 -0.213118   
715    -1.195937 -0.857109      -0.167190       0.551917 -0.708090 -0.172168   

     DiabetesPedigreeFunction       Age  
0                    0.598763  1.588547  
1                   -0.348179 -0.135198  
2                    0.753156 -0.044475  
3                   -0.979475 -1.042433  
4                   -0.862822 -0.225922  
..                        ...       ...  
711                 -0.965751  2.767952  
712                 -0.385920 -0.498092  
713                 -0.711860 -0.225922  
714                 -0.355041  1.316377  
715                 -0.471694 -0.860986  

[716 rows x 8 columns]

In [63]:
#checking Multicollinearity using VIF score
from statsmodels.stats.outliers_influence import variance_inflation_factor
def vif_score(x):
    scaler = StandardScaler()
    arr = scaler.fit_transform(x)
    return pd.DataFrame([[x.columns[i] , variance_inflation_factor(arr,i)] for i in range(arr.shape[1])] , columns  = ['Features','VIF_SCORE'])

In [64]:
vif_score(x)

Features  VIF_SCORE
0               Pregnancies   1.441729
1                   Glucose   1.307682
2             BloodPressure   1.242835
3             SkinThickness   1.461282
4                   Insulin   1.315295
5                       BMI   1.436940
6  DiabetesPedigreeFunction   1.035243
7                       Age   1.580551

In [71]:
#Training and Testing
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x_df , y , test_size = .20 , random_state = 144)


In [72]:
x_train

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
122     1.474601 -1.140437       0.169453       0.551917 -0.708090  0.906176   
273    -0.110534  1.283597      -1.850402      -0.634635 -0.708090 -1.332413   
173     1.474601  1.913216      -0.335511       1.118910  3.737635 -0.213118   
599    -0.432926 -0.542299       0.001131       0.438518  0.657062 -0.554366   
591     0.330085 -0.510818       0.169453      -0.634635 -0.708090 -0.390567   
..           ...       ...            ...            ...       ...       ...   
643     1.093096  0.276206      -0.335511       2.593092  0.414568  0.933476   
422     0.330085 -1.077476      -0.335511       0.211721 -0.070420 -0.199468   
216    -0.051421  0.055839      -0.335511      -0.634635 -0.708090  0.455729   
444    -0.432926  1.189154      -0.167190       0.438518  2.237764  0.523978   
359    -1.195937 -0.636742      -0.503832       0.325119  1.052238  0.046231   

     DiabetesPedigreeFunction       Age  
122                  0.015502  0.590589  
273                 -0.680982  2.949399  
173                  0.557592  2.495782  
599                  0.952152 -0.498092  
591                 -1.027508  1.407100  
..                        ...       ...  
643                 -0.046256  0.953483  
422                 -0.303577 -0.770262  
216                 -0.200648 -0.316645  
444                 -0.372196  0.227696  
359                 -0.029101  0.862760  

[572 rows x 8 columns]

In [76]:
y_train

133    0
294    0
186    1
644    0
636    0
      ..
693    1
457    0
233    0
480    1
390    0
Name: Outcome, Length: 572, dtype: int64

In [73]:
x_test

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
88     -0.814432 -0.888590      -0.840475       0.211721 -0.708090 -0.008369   
49      0.330085 -1.014514      -0.503832      -0.582070 -0.501521 -0.991164   
514     1.093096  0.118801      -0.167190       0.778714  1.222882 -0.841015   
438    -0.051421 -0.196009      -0.672154      -0.634635 -0.708090 -0.376917   
641     1.474601 -0.416375       0.674416      -0.634635 -0.708090 -0.963864   
..           ...       ...            ...            ...       ...       ...   
200     0.330085 -0.353413      -0.840475       1.685903  0.450493  0.564928   
439    -0.110534  0.528054       1.011059       0.098322 -0.708090 -0.595316   
491    -0.814432  0.055839      -1.008796      -0.922266  0.243924 -0.254068   
14      1.093096 -0.636742      -0.242474      -0.634635 -0.708090 -0.226768   
357     0.330085  0.748420       0.842738      -0.015076  1.851570  0.046231   

     DiabetesPedigreeFunction       Age  
88                  -1.106420 -0.770262  
49                  -0.379058 -0.225922  
514                 -1.000060  0.409142  
438                 -1.120144 -0.770262  
641                  1.384452  0.136972  
..                        ...       ...  
200                  0.211066 -0.679539  
439                 -0.759894  2.405058  
491                  0.907549 -0.951709  
14                   0.108137 -0.044475  
357                 -0.001653  2.314335  

[144 rows x 8 columns]

In [75]:
y_test

96     0
52     0
555    0
474    0
690    0
      ..
216    1
475    0
530    0
15     1
388    1
Name: Outcome, Length: 144, dtype: int64

In [79]:
#Logistic Regression 
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(x_train , y_train)

LogisticRegression()

In [80]:
logr.predict(x_test)

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [81]:
logr.score(x_test,y_test)

0.8125

In [94]:
logr.predict_proba(x_test.head(2))

array([[0.93102906, 0.06897094],
       [0.92746314, 0.07253686]])

In [87]:
x_test.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin       BMI  \
88    -0.814432 -0.88859      -0.840475       0.211721 -0.70809 -0.008369   

    DiabetesPedigreeFunction       Age  
88                  -1.10642 -0.770262

In [102]:
import pickle
pickle.dump(logr,open('log_diabetes.sav','wb'))

In [103]:
log_saved = pickle.load(open('log_diabetes.sav','rb'))

In [105]:
log_saved

LogisticRegression()

In [106]:
log_saved.score(x_test,y_test)

0.8125

In [ ]:
log_saved.score()